social_network/main/routes.py
from social_network.models import User, Post, Friendship, Message
from social_network import db
from datetime import datetime
from social_network.main.forms import (
    NewPostForm
)
from flask import render_template, url_for, redirect, request, Blueprint
from flask_login import login_required, current_user
from sqlalchemy import or_, and_


main = Blueprint("main", __name__)


@login_required
def getFriendship(f_id):
    return Friendship.query.filter(
        or_(Friendship.user1_id == current_user.id,
            Friendship.user2_id == current_user.id)
    ).filter(
        or_(Friendship.user1_id == f_id,
            Friendship.user2_id == f_id)
    ).first()


@main.route("/sql/create_all")
def createAll():
    db.create_all()
    return redirect(url_for("main.profile"))


@main.route("/")
@main.route("/<user>")
@login_required
def profile(user=None):
    u = User.query.filter_by(username=user).first()
    if u is None:
        u = current_user
        friend = None
    else:
        friend = bool(Friendship.query.filter_by(
            user2_id=u.id, user1_id=current_user.id).scalar())
    return render_template(
        "main/profile_page.html",
        user=u,
        posts=Post.query.filter_by(
            user_id=u.id
        ).order_by(
            Post.date_created.desc()
        ),
        f=friend
    )


@main.route("/search", methods=["GET", "POST"])
@main.route("/search/<key>", methods=["GET", "POST"])
@login_required
def search(key=None):
    if request.method == "POST":
        key = request.form['search']
        return redirect('/search/' + key)
    result = User.query.filter(
        User.id != current_user.id
    ).filter(
        or_(User.name.contains(key),
            User.username.contains(key))
    ).all()
    print(result)
    my_friends = User.query.filter(
        User.id != current_user.id
    ).filter(
        or_(User.id == Friendship.user1_id,
            User.id == Friendship.user2_id)
    ).filter(
        or_(Friendship.user1_id == current_user.id,
            Friendship.user2_id == current_user.id)
    ).all()
    friends = dict((
        u.id,
        bool(u in my_friends)
    ) for u in result)
    print(friends)
    return render_template("main/user_list.html", users=result, f=friends)


@main.route("/new_post", methods=["GET", "POST"])
@login_required
def newpost():
    form = NewPostForm()
    if form.validate_on_submit():
        newPost = Post(
            text=form.text.data,
            user_id=current_user.id,
        )
        db.session.add(newPost)
        db.session.commit()
        return redirect(url_for("main.profile"))
    return render_template("main/new_post.html", form=form)


@main.route("/add_friend", methods=["POST"])
@login_required
def addFriend():
    f_id = int(request.form['friend_id'])
    f = getFriendship(f_id)
    if f is None:
        new_f = Friendship(user1_id=int(current_user.id), user2_id=int(f_id))
        db.session.add(new_f)
        db.session.commit()
    return 'success'


@main.route("/del_friend", methods=["POST"])
@login_required
def delFriend():
    f_id = int(request.form['friend_id'])
    f = getFriendship(f_id)
    if f:
        db.session.delete(f)
        db.session.commit()
    return 'success'


@main.route("/friends")
@login_required
def friends():
    friends = User.query.filter(
        User.id != current_user.id
    ).filter(
        or_(User.id == Friendship.user1_id,
            User.id == Friendship.user2_id)
    ).filter(
        or_(Friendship.user1_id == current_user.id,
            Friendship.user2_id == current_user.id)
    ).all()
    return render_template("main/user_list.html", users=friends, f=None)


@main.route("/chat/<username>", methods=["GET", "POST"])
@login_required
def chat(username):
    u = User.query.filter(User.username == username).first()
    print(u)
    if u is None:
        return redirect(url_for("main.profile"))
    if request.method == "POST":
        text = request.form['message']
        new_m = Message(
            text=text,
            user1_id=current_user.id,
            user2_id=u.id
        )
        db.session.add(new_m)
        db.session.commit()
    m = Message.query.filter(
        or_(
            and_(Message.user1_id == u.id, Message.user2_id == current_user.id),
            and_(Message.user2_id == u.id, Message.user1_id == current_user.id)
        )
    ).order_by(Message.date_created.desc()).all()
    print(m)
    return render_template("main/chat_page.html", user=u, messages=reversed(m), my_id=current_user.id)

social_network/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from social_network import db, bcrypt
from social_network.models import User
from social_network.users.forms import (
    RegistrationForm,
    LoginForm,
    EditForm
)
from social_network.users.utils import save_picture
from datetime import datetime


users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.profile"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data,
            password=hashed_password,
            name=form.name.data,
            gender=bool(int(form.gender.data)),
            city=form.city.data,
            born=int(form.born.data),
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("main.profile"))
    return render_template("users/register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.profile"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return (
                redirect(next_page)
                if next_page
                else redirect(url_for("main.profile"))
            )
        else:
            flash(
                f"Sorry, the Login was unseccesfull. Please check your credentials and try again!",
                "primary",
            )
    return render_template("users/login.html", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("users.login"))


@users.route("/edit", methods=["GET", "POST"])
@login_required
def edit():
    form = EditForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.gender = bool(int(form.gender.data))
        current_user.city = form.city.data
        current_user.born = form.born.data
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        db.session.commit()
        return redirect(url_for("main.profile"))
    form.fill()
    return render_template("users/edit.html", form=form)

social_network/templates/_render_field.html
{% macro render_field(field) %}
	<div>
		{{ field.label(class="form-control-label") }}
		{% if field.errors %}
			{{ field(class="form-control form-control-lg is-invalid")}}
			<div class="invalid-feedback">
				{% for error in field.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% else %}
			{{ field(class="form-control form-control-ls") }}
		{% endif %}
	</div>
{% endmacro %}

social_network/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"> {% if title %}
    <title>Social Network</title> - {{ title }}</title>
    {% else %}
    <title>Social Network - The best way to comunicate!</title>
    {% endif %} {% block head%} {% endblock head%}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'main.css') }}">

</head>

<body>
    <nav>
        <form action="/search" method="post">
            <input type="search" name="search" placeholder="Search people" aria-label="Search" required>
            <input type="submit" value="Search">
        </form>

        <div>
            <a class="btn" href="{{ url_for('main.profile') }}">My Page</a>
            <a class="btn" href="{{ url_for('main.newpost') }}">New Post</a>
            <a class="btn" href="{{ url_for('main.friends') }}">My Friends</a>
        </div>
        <div>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('users.logout') }}">Logout</a> {% else %}
            <a href="{{ url_for('users.login') }}">Login</a>
            <a href="{{ url_for('users.register') }}">Register</a> {% endif %}
        </div>
    </nav>
    <div id="content">

        {% block content %} {% endblock content%}

    </div>

    {% block scripts %} {% endblock scripts %}
</body>

</html>

social_network/templates/simple_layout.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='simple.css') }}"> {% if title %}
    <title>Social Network</title> - {{ title }}</title>
    {% else %}
    <title>Social Network - The best way to comunicate!</title>
    {% endif %}
</head>

<body>
    <header>
        <nav>
            <a href="{{ url_for('main.profile', user='') }}">
                <h1>Social Network</h1>
            </a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('users.logout') }}">Logout</a> {% else %}
            <a href="{{ url_for('users.login') }}">Login</a>
            <a href="{{ url_for('users.register') }}">Register</a> {% endif %}
        </nav>
    </header>
    <section>
        {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
        <div class="m">
            {{ message }}
        </div>
        {% endfor %} {% endif %} {% endwith %} {% block content %} {% endblock %}
    </section>

</body>

</html>